IMAGE_DIR="../XProNet-main/data/iu_xray/images"
ANN_PATH="../XProNet-main/data/iu_xray/annotation_disease.json"
LABEL_PATH = "../XProNet-main/data/iu_xray/labels/labels_14.pickle"
INIT_PROTYPES_PATH = "../XProNet-main/data/iu_xray/init_prototypes.pt"
DATASET_NAME="iu_xray"
MAX_SEQ_LENGTH=60
THRESHOLD=3
EPOCHS=150
BATCH_SIZE=4
LR_VE=1e-4
LR_ED=5e-4
STEP_SIZE=10
GAMMA=0.8
NUM_LAYERS=3
TOPK=32
CMM_SIZE=2048
CMM_DIM=512
SEED=7580
BEAM_SIZE=3
SAVE_DIR="results/iu_xray/"
LOG_PERIOD=50
EARLY_STOP=40
D_IMG_EBD = 2048
D_TXT_EBD = 768
NUM_CLUSTER = 14
RESUME = "../ComgXpro/results/iu_xray/model_best.pth"